config/routes.rb
Rails.application.routes.draw do
  resources :todo_projects do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  
  resources :todo_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  root "todo_projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_project
end

app/models/todo_project.rb
class TodoProject < ApplicationRecord
	has_many :todo_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_language

	private

	def set_language
	  cookies[:lang] = params[:lang] unless params[:lang].blank?
	  locale = cookies[:lang] || I18n.default_locale
	  I18n.locale = locale if locale && I18n.available_locales.include?(locale.to_sym)

	end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_related_todo_project, except: [:update]

  before_action :set_todo_item, except: [:create]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create

    @todo_item = @todo_related_project.todo_items.create(todo_item_params)

    uploaded_io = params[:todo_item][:todo_file]
    if !uploaded_io.nil?
      @todo_item.todo_file = uploaded_io.original_filename #put normal name
      File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end
    end


    respond_to do |format|
      if @todo_item.save
        # format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.html { redirect_to @todo_related_project, notice: 'New todo item was successfully added.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    @todo_related_project = TodoProject.find(@todo_item.todo_project_id)
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_related_project, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy

    @todo_item = @todo_related_project.todo_items.find(params[:id])
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_related_project, notice: 'Todo item was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def complete
    if (!@todo_item.is_done.nil? && @todo_item.is_done == true)
      @todo_item.update_attribute(:is_done, false)
    elsif (!@todo_item.is_done.nil? && @todo_item.is_done == false)
      @todo_item.update_attribute(:is_done, true)
    else
      @todo_item.update_attribute(:is_done, true)
    end
    if @todo_item.is_done
      respond_to do |format|
        format.html { redirect_to @todo_related_project, notice: 'Todo item was marked as done' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @todo_related_project, notice: 'Todo item was set as undone' }
        format.json { head :no_content }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item

      @todo_item = @todo_related_project.todo_items.find(params[:id]) if !@todo_related_project.nil?
      if @todo_related_project.nil?
        @todo_item = TodoItem.find(params[:id])
      end
    end

    def set_related_todo_project
     @todo_related_project = TodoProject.find(params[:todo_project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      
      params[:todo_item].permit(:title, :task_content, :implement_before, :order_type, :todo_file)
    end
end

app/controllers/todo_projects_controller.rb
class TodoProjectsController < ApplicationController
  before_action :set_todo_project, only: [:show, :edit, :update, :destroy]

  # GET /todo_projects
  # GET /todo_projects.json
  def index
    @todo_projects = TodoProject.all
  end

  # GET /todo_projects/1
  # GET /todo_projects/1.json
  def show
  end

  # GET /todo_projects/new
  def new
    @todo_project = TodoProject.new
  end

  # GET /todo_projects/1/edit
  def edit
  end

  # POST /todo_projects
  # POST /todo_projects.json
  def create
    @todo_project = TodoProject.new(todo_project_params)

    respond_to do |format|
      if @todo_project.save
        format.html { redirect_to @todo_project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @todo_project }
      else
        format.html { render :new }
        format.json { render json: @todo_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_projects/1
  # PATCH/PUT /todo_projects/1.json
  def update
    respond_to do |format|
      if @todo_project.update(todo_project_params)
        format.html { redirect_to @todo_project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_project }
      else
        format.html { render :edit }
        format.json { render json: @todo_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_projects/1
  # DELETE /todo_projects/1.json
  def destroy
    Rails.logger.info "We are deleting project"
    @todo_project.destroy
    respond_to do |format|
      format.html { redirect_to todo_projects_url, notice: 'Project was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_project
      @todo_project = TodoProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_project_params
      params.require(:todo_project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def to_priority_string(number)
  	if number == 1
  		return "<strong > Low</strong>"
  	elsif number == 2
  		return "<strong > Normal</strong>"
  	else
  		return "<strong > High</strong>"
  	end
  end

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_projects_helper.rb
module TodoProjectsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Todo List Application</a> -->
      <%= link_to 'Todo List Application', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        

        <li><a href="#"><%= I18n.t("signin") %></a></li>
        <li><a href="#"><%= I18n.t("signup") %></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.t("language") %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% I18n.available_locales.each do |lang| %>
              <li><a href="?lang=<%= lang %>"><span>
              <%= title_ = (lang.to_s == "en" ? "English" : "Ukrainian") %> </span> <img src="/<%= lang %>.png" class="lang"></img></a>
              </li>
            <% end %>

          </ul>
        </li>
        <li><a href="https://github.com/dev20600/vcraft_test_assignment_/"><i class="fab fa-github"></i> <%= I18n.t("github") %></a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div >
      <%= render 'layouts/navigation' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_project, @todo_project.todo_items.build], :html => {:class => 'custom_class3'}) do |f| %>
 <%= f.text_field :title, label: 'Title', placeholder: "Title", class: 'padng' %>
 <%= f.text_field :task_content, label: 'Task details', placeholder: "Details", class: 'padng' %>
 <%= f.text_field :implement_before, label: 'Date', data:{ provide:'datepicker' }, :placeholder => 'dd/mm/yyyy', class: 'datapiecker_class padng' %>

  <%= f.select :order_type, [['Low Priority', 1], ['Normal Priority', 2], ['High Priority', 3]], {}, {class: "select-wrapper-select1"} %>
  <label class="custom-file-upload1">
  <%= f.file_field :todo_file, class: 'file_up', style: "color: green; display: none;" %>
    <i class="fas fa-cloud"></i> <%=I18n.t("file_upload")%>
  </label>
  <!-- <div class="select-arrow-1"></div> -->

 <%= f.submit I18n.t("add")%>
<% end %>

<script>
  $( document ).ready(function() {
    $('.datapiecker_class').datepicker({format: 'dd/mm/yyyy'});
  });
</script>

app/views/todo_items/_form3.html.erb
<%= form_with(model: todo_item, local: true, class: :custom_class3) do |form_| %>
  <% if todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <%= form_.text_field :title, label: 'Title', placeholder: "Title", class: 'padng' %>
 <%= form_.text_field :task_content, label: 'Task details', placeholder: "Details", class: 'padng' %>
 <%= form_.text_field :implement_before, label: 'Date', data:{ provide:'datepicker' }, :placeholder => 'dd/mm/yyyy', class: 'datapiecker_class1 padng' %>

 <%= form_.select :order_type, [['Low Priority', 1], ['Normal Priority', 2], ['High Priority', 3]], {}, {class: "select-wrapper-select1"} %>

 <%= form_.submit I18n.t("save_changes")%>
<% end %>

<script>
  $( document ).ready(function() {
    $('.datapiecker_class1').datepicker({format: 'dd/mm/yyyy'});
  });
</script>

app/views/todo_items/_todo_item.html.erb
<div class="row row2">
  <!-- <p><%= todo_item.title %></p> -->
  <% some_local_ = 125 %>
  <% some_local_ = 1 if !todo_item.is_done.nil? && todo_item.is_done == true %>
  <p><span <%  if some_local_ == 1%> class='task_ready'<% end %> ><%= todo_item.task_content %></span> | 

  <%  if !todo_item.implement_before.nil? %>
    <%=I18n.t("relase_date")%>: <strong><%= todo_item.implement_before.strftime('%d/%m/%Y') %></strong> | 
  <% end %>

  <%=I18n.t("priority")%>: <%= to_priority_string(todo_item.order_type).html_safe %> |
  <% title_ = (some_local_==1 ? I18n.t("set_undone") : I18n.t("set_as_done") ) %>
  
  <% if !todo_item.todo_file.blank? %>
  <%= link_to todo_item.todo_file, '/uploads/'+todo_item.todo_file %> | 
  <% end %>

  <%= link_to title_, complete_todo_project_todo_item_path(@todo_project, todo_item.id), method: :patch %> | 
  <%= link_to I18n.t("modify"), edit_todo_project_todo_item_path(@todo_project, todo_item.id) %> | 
  <%= link_to I18n.t("delete"), todo_project_todo_item_path(@todo_project, todo_item.id), method: :delete, data: { confirm: I18n.t("confirm") } %> </p>
</div>

app/views/todo_items/edit.html.erb
<main>
  <div class="container">
  	<div class="row">
  		<h3><%=I18n.t("update_todo")%></h3>
  	</div>

	<div class="row">
		<%= render 'form3', todo_item: @todo_item %>
	</div>

	<div class="row">

		<%= link_to I18n.t("back"), @todo_related_project %>
	
	</div> 
  </div>
</main>

app/views/todo_items/index.html.erb
<main>
  <div class="container">
    <div class="row color2">
      <p id="notice"><%= notice %></p>
    </div>

    <div class="row">
      <h3>Todo Items</h3>
    </div>

    <div class="row">
      <table>
        <thead>
          <tr>
            <th class="mycellstyle1">Task Title</th>
            <th class="mycellstyle">Details</th>      
            <th class="mycellstyle">Release date</th>      
            <th class="mycellstyle">Priority</th>      
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @todo_items.each do |todo_item| %>
            <tr>
              <td class="mycellstyle1"><%= todo_item.title %></td>
              <td class="mycellstyle"><%= todo_item.task_content %></td>
              <td class="mycellstyle"><%= todo_item.implement_before %></td>
              <td class="mycellstyle"><%= todo_item.order_type %></td>

              <td class="mycellstyle"><%= link_to 'Show', todo_item %></td>
              <td class="mycellstyle"><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
              <td class="mycellstyle"><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>

    <div class="row">
      <%= link_to 'New Todo Item', new_todo_item_path %>
    </div>

  </div>
</main>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form', todo_item: @todo_item %>

<%= link_to 'Back', todo_items_path %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_projects/_form.html.erb
<%= form_with(model: todo_project, local: true, class: :custom_class1) do |form| %>
  <% if todo_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_project.errors.count, "error") %> prohibited this todo_project from being saved:</h2>

      <ul>
      <% todo_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row row2">
    <div>
      <%= form.label I18n.t("simple_title") %>
    </div>
    <div>
      <%= form.text_field :title, class: :inpt %>
    </div>

    
  </div>

  <div class="row row2">
    <div>
      <%= form.label I18n.t("project_description") %>
    </div>
    <div>
      <%= form.text_area :description, class: :inpt %>
    </div>
    
    
  </div>

  <div class="row row2">
    <%= form.submit I18n.t("project_start") %>
  </div>
<% end %>

app/views/todo_projects/_form2.html.erb
<%= form_with(model: todo_project, local: true, class: :custom_class1) do |form| %>
  <% if todo_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_project.errors.count, "error") %> prohibited this todo_project from being saved:</h2>

      <ul>
      <% todo_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row row2">
    <div>
      <%= form.label I18n.t("simple_title") %>
    </div>
    <div>
      <%= form.text_field :title, class: :inpt %>
    </div>

    
  </div>

  <div class="row row2">
    <div>
      <%= form.label I18n.t("project_description") %>
    </div>
    <div>
      <%= form.text_area :description, class: :inpt %>
    </div>
    
    
  </div>

  <div class="row row2">
    <%= form.submit I18n.t("save") %>
  </div>
<% end %>

app/views/todo_projects/edit.html.erb
<main>
  <div class="container">
  	<div class="row">
		<h3><%= I18n.t("update_project")%></h3>
	</div>

	<div class="row">
		<%= render 'form2', todo_project: @todo_project %>

		<%= link_to I18n.t("project_page"), @todo_project %> |
		<%= link_to I18n.t("back"), todo_projects_path %>
	</div>
  </div>
</main>

app/views/todo_projects/index.html.erb
<main>
  <div class="container">
    <div class="row colo1">
      <p id="notice"><%= notice %></p>
    </div>

    <div class="row">
      <h3><%=I18n.t("projects_list")%></h3>
    </div>

    <div class="row">
      <table>
        <thead>
          <tr>
            <th class="mycellstyle1"><%=I18n.t("simple_title")%></th>
            <th class="mycellstyle"><%=I18n.t("project_description")%></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @todo_projects.each do |todo_project| %>
            <tr>
              <td class="mycellstyle1"><%= todo_project.title %></td>
              
              <td class="mycellstyle"><%= todo_project.description %></td>
              
              <td class="mycellstyle"><%= link_to I18n.t("details"), todo_project %></td>
              
              <td class="mycellstyle"><%= link_to I18n.t("modify"), edit_todo_project_path(todo_project) %></td>
              
              <td class="mycellstyle"><%= link_to todo_project, method: :delete, data: { confirm: I18n.t("confirm") } do %><i class="fas fa-trash-alt"></i><% end %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>

    <div class="row">
      <%= link_to I18n.t("crete_project"), new_todo_project_path %>
    </div>

  </div>
<main>

app/views/todo_projects/new.html.erb
<main>
  <div class="container">
  	<div class="row">
		<h3><%=I18n.t("project_create")%></h3>
	</div>
    <div class="row">
		<%= render 'form', todo_project: @todo_project %>


		<%= link_to I18n.t("back"), root_path %>
	</div>
  </div>
</main>

app/views/todo_projects/show.html.erb
<main>
  <div class="container">
	<div class="row colo1" >
		<p id="notice"><%= notice %></p>
	</div>

  	<div class="row">
		<h3><%=I18n.t("project_details")%></h3>
	</div>

	<div class="row">
		<p>
		  <strong><%=I18n.t("simple_title")%>:</strong>
		  <%= @todo_project.title %>
		</p>
	</div>

	<div class="row">
	<p>
	  <strong><%=I18n.t("project_description")%>:</strong>
	  <%= @todo_project.description %>
	</p>
	</div>

	<div class="row">
		<div id="todo_items_wrapper">
			<% if (@todo_project.todo_items.size > 0) %>
				<p>

					<strong><%=I18n.t("title_todo_list")%></strong>
				</p>
			<% end %>
		 <%= render @todo_project.todo_items %>
		 <div id="form">
		  <%= render "todo_items/form" %>
		 </div>
		</div>
	</div>
	<div class="row">
		<%= link_to I18n.t("edit_project_details"), edit_todo_project_path(@todo_project) %> |

		<%= link_to I18n.t("back"), root_path %>
	</div>
  </div>
</main>